version: "3"
services:
  guessing_game:
    build: ./guessing_game
    volumes:
      - ./guessing_game:/app
    command: sleep infinity
  variables:
    build: ./variables
    volumes:
      - ./variables:/app
    command: sleep infinity
  functions:
    build: ./functions
    volumes:
      - ./functions:/app
    command: sleep infinity
  ownerships:
    build: ./ownerships
    volumes:
      - ./ownerships:/app
    command: sleep infinity
  slices:
    build: ./slices
    volumes:
      - ./slices:/app
    command: sleep infinity
